/*
 * Copyright 2023-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.ai.model;

/**
 * This interface provides methods to access the main output of the AI model and the
 * metadata associated with this result. It is designed to offer a standardized and
 * comprehensive way to handle and interpret the outputs generated by AI models, catering
 * to diverse AI applications and use cases.
 *
 * @param <T> the type of the output generated by the AI model
 * @author Mark Pollack
 * @since 0.8.0
 */
/**
 * 【中文说明】ModelResult 表示 AI 模型产出的<b>单条</b>结果，是 {@link ModelResponse} 列表中的元素类型。
 *
 * <p>
 * 用途：把"输出内容"与"该条输出的元数据"打包在一起。之所以要单独抽象一层而不是直接返回字符串，
 * 是因为每条结果除了正文之外还携带自身的状态信息（如结束原因 finishReason、内容安全过滤结果等），
 * 这些信息是逐条不同的，无法放在整次响应的元数据里。
 *
 * <p>
 * 关键泛型参数 {@code T}：输出的具体类型。例如 Generation 实现
 * {@code ModelResult<AssistantMessage>}；Embedding 实现 {@code ModelResult<float[]>}。
 *
 * <p>
 * 三层结构总览：{@code ModelResponse}（整次响应）-> {@code ModelResult}（单条结果）->
 * {@code T}（真正的输出数据）。
 *
 * @param <T> AI 模型生成的输出的类型
 * @author Mark Pollack
 * @since 0.8.0
 */
public interface ModelResult<T> {

	/**
	 * Retrieves the output generated by the AI model.
	 * @return the output generated by the AI model
	 */
	// 【中文】获取这条结果的实际输出内容，即开发者最终关心的数据（如助手回复消息、向量数组、图片等）。
	T getOutput();

	/**
	 * Retrieves the metadata associated with the result of an AI model.
	 * @return the metadata associated with the result
	 */
	// 【中文】获取<b>该条结果自身</b>的元数据（区别于 ModelResponse#getMetadata 的整次响应元数据）。
	// 常见内容：finishReason（stop/length/tool_calls 等结束原因）、内容过滤标记、日志概率等。
	ResultMetadata getMetadata();

}
