/*
 * Copyright 2023-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.ai.model;

import java.util.List;

import org.jspecify.annotations.Nullable;

/**
 * Interface representing the response received from an AI model. This interface provides
 * methods to access the main result or a list of results generated by the AI model, along
 * with the response metadata. It serves as a standardized way to encapsulate and manage
 * the output from AI models, ensuring easy retrieval and processing of the generated
 * information.
 *
 * @param <T> the type of the result(s) provided by the AI model
 * @author Mark Pollack
 * @since 0.8.0
 */
/**
 * 【中文说明】ModelResponse 是所有"AI 模型返回结果"的统一抽象接口，与 {@link ModelRequest} 成对出现。
 *
 * <p>
 * 设计思想：一次模型调用可能产出<b>多个</b>结果（例如设置 n=3 让 LLM 生成 3 个候选回答，
 * 或一次为多段文本生成多个向量），因此接口同时提供：
 * <ul>
 * <li>{@link #getResults()} —— 完整结果列表；</li>
 * <li>{@link #getResult()} —— 便捷方法，取第一个（最常用的）结果；</li>
 * <li>{@link #getMetadata()} —— 与整次调用相关的元数据（token 用量、限流信息、模型 ID 等）。</li>
 * </ul>
 *
 * <p>
 * 关键泛型参数 {@code T}：被约束为 {@link ModelResult} 的子类型，形成"响应 -> 结果 -> 结果元数据"
 * 的三层嵌套结构。注意这里的嵌套通配符 {@code ModelResult<?>}：只要求元素符合结果契约，
 * 不限制结果内部承载的输出类型。
 *
 * <p>
 * 典型用法：ChatResponse、EmbeddingResponse、ImageResponse 等均实现本接口。
 *
 * @param <T> AI 模型产出的结果类型
 * @author Mark Pollack
 * @since 0.8.0
 */
public interface ModelResponse<T extends ModelResult<?>> {

	/**
	 * Retrieves the (first) result of the AI model.
	 * @return the result generated by the AI model
	 */
	// 【中文】便捷方法：获取第一个结果。绝大多数场景模型只返回一个结果，故直接用此方法即可。
	// 标注 @Nullable 是重要的空值处理约定：当结果列表为空（例如请求被内容安全策略拦截、
	// 或流式响应中某些仅承载元数据的空片段）时会返回 null，调用方需做判空。
	@Nullable T getResult();

	/**
	 * Retrieves the list of generated outputs by the AI model.
	 * @return the list of generated outputs
	 */
	// 【中文】获取全部结果列表。当请求要求生成多个候选（如 n>1）或批量处理多条输入时，
	// 需要用本方法遍历。与 getResult() 不同，此方法约定返回非 null 的列表（可能为空列表）。
	List<T> getResults();

	/**
	 * Retrieves the response metadata associated with the AI model's response.
	 * @return the response metadata
	 */
	// 【中文】获取整次响应级别的元数据，如 token 消耗（Usage）、限流配额（RateLimit）、
	// 模型标识、请求 ID 等。注意区分：这是"整次调用"的元数据，
	// 而单条结果自身的元数据（如结束原因 finishReason）在 ModelResult#getMetadata() 中。
	ResponseMetadata getMetadata();

}
