/*
 * Copyright 2023-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.ai.model;

/**
 * Interface representing metadata associated with the results of an AI model. This
 * interface focuses on providing additional context and insights into the results
 * generated by AI models. It could include information like computation time, model
 * version, or other relevant details that enhance understanding and management of AI
 * model outputs in various applications.
 *
 * @author Mark Pollack
 * @since 0.8.0
 */
/**
 * 【中文说明】ResultMetadata 是"单条结果元数据"的<b>标记接口</b>（空接口，无方法）。
 *
 * <p>
 * 用途：为 {@link ModelResult#getMetadata()} 提供统一的返回类型。由于不同模态能提供的
 * 逐条元数据差别很大（聊天有 finishReason，嵌入几乎没有额外信息，图像有修订后的提示词等），
 * 所以同样采用空标记接口的设计，把字段定义留给子类型。
 *
 * <p>
 * 典型实现：ChatGenerationMetadata（含 finishReason、contentFilters）、
 * EmbeddingResultMetadata、ImageGenerationMetadata 等。
 *
 * <p>
 * 注意与 {@link ResponseMetadata} 区分：本接口描述"一条结果"，后者描述"整次调用"，
 * 且后者是带 Map 语义的、有实际方法的接口。
 *
 * @author Mark Pollack
 * @since 0.8.0
 */
public interface ResultMetadata {

}
