/*
 * Copyright 2023-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.ai.moderation;

import org.springframework.ai.model.ResultMetadata;

/**
 * An interface that represents metadata associated with the results of a moderation
 * generation process. This interface extends the ResultMetadata interface, which provides
 * general information about the results generated by an AI model.
 *
 * @author Ahmed Yousri
 * @since 1.0.0
 */
/**
 * 【中文说明】单条审核结果的元数据接口。
 *
 * <p>
 * 继承自通用的 {@code ResultMetadata}，用于承载与「单个生成结果」相关的附加信息。
 *
 * <p>
 * 这里是一个<b>空接口（标记接口）</b>——公共层不预设任何字段，纯粹起类型约束作用，
 * 由各厂商实现按需扩展。{@code Generation} 类中用匿名实现
 * {@code new ModerationGenerationMetadata(){}} 作为「无元数据」的默认空对象。
 */
public interface ModerationGenerationMetadata extends ResultMetadata {

}
